services:
  explorer:
    image: kuzudb/explorer:0.7.0
    restart: unless-stopped
    environment:
      - MODE=READ_WRITE
    ports:
      - 8000:8000
    volumes:
      - ./ex_db_kuzu:/database
      - ./data:/data
